apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidato
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candidato
  template:
    metadata:
      labels:
        app: candidato
    spec:
      containers:
      - name: candidato
        image: 798178280816.dkr.ecr.us-east-1.amazonaws.com/candidato:latest
        ports:
        - containerPort: 5001
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://postgres:postgres@database-1.cfgkb3tpxr7g.us-east-1.rds.amazonaws.com:5432/postgres"            
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - managed-nodes
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - candidato
            topologyKey: kubernetes.io/hostname
            namespaces:
            - default