import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://bucket-abcjobs-angular.s3-website-us-east-1.amazonaws.com/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByLabel('Correo').click();
  await page.getByLabel('Correo').fill('jorge@gmail.com');
  await page.getByLabel('Correo').press('Tab');
  await page.getByLabel('Contraseña', { exact: true }).fill('qwerty');
  await page.locator('div').filter({ hasText: /^Rol$/ }).nth(2).click();
  await page.getByText('Candidato').click();
  await page.getByRole('button', { name: 'Ingresar' }).click();
  await page.getByRole('link', { name: 'Información Académica' }).click();
  await page.getByRole('link', { name: 'Agregar nueva' }).click();
  await page.getByLabel('Título obtenido').click();
  await page.getByLabel('Título obtenido').press('CapsLock');
  await page.getByLabel('Título obtenido').fill('Locutor');
  await page.getByText('Institución').click();
  await page.getByLabel('Institución').press('CapsLock');
  await page.getByLabel('Institución').fill('Univalle');
  await page.locator('mat-form-field').filter({ hasText: 'Fecha de inicioMM/DD/YYYY' }).getByLabel('Open calendar').click();
  await page.getByLabel('November 5, 2023').click();
  await page.locator('mat-form-field').filter({ hasText: 'Fecha de finalizaciónMM/DD/YYYY' }).getByLabel('Open calendar').click();
  await page.getByLabel('Choose month and year').click();
  await page.getByLabel('2025').click();
  await page.getByLabel('November 2025').click();
  await page.getByLabel('November 5, 2025').click();
  await page.getByLabel('Tipo de estudio').click();
  await page.getByLabel('Tipo de estudio').press('CapsLock');
  await page.getByLabel('Tipo de estudio').fill('Profesional');
  await page.getByRole('button', { name: 'Guardar' }).click();
});
