name: CI Angular App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - run: Run Angular tests
      - run: ng test --no-watch --no-progress --browsers=ChromeHeadless
